/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanHoRouteImport } from './routes/can-ho'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as KhamPhaRouteImport } from './routes/kham-pha'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as SuaAnhRouteImport } from './routes/sua-anh'
import { Route as TienIchRouteImport } from './routes/tien-ich'
import { Route as TinTucRouteImport } from './routes/tin-tuc'
import { Route as TinTucIndexRouteImport } from './routes/tin-tuc.index'
import { Route as TinTucSlugRouteImport } from './routes/tin-tuc.$slug'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanHoRoute = CanHoRouteImport.update({
  id: '/can-ho',
  path: '/can-ho',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const KhamPhaRoute = KhamPhaRouteImport.update({
  id: '/kham-pha',
  path: '/kham-pha',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const SuaAnhRoute = SuaAnhRouteImport.update({
  id: '/sua-anh',
  path: '/sua-anh',
  getParentRoute: () => rootRouteImport,
} as any)
const TienIchRoute = TienIchRouteImport.update({
  id: '/tien-ich',
  path: '/tien-ich',
  getParentRoute: () => rootRouteImport,
} as any)
const TinTucRoute = TinTucRouteImport.update({
  id: '/tin-tuc',
  path: '/tin-tuc',
  getParentRoute: () => rootRouteImport,
} as any)
const TinTucIndexRoute = TinTucIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TinTucRoute,
} as any)
const TinTucSlugRoute = TinTucSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TinTucRoute,
} as any)

const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/can-ho': typeof CanHoRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/kham-pha': typeof KhamPhaRoute
  '/lien-he': typeof LienHeRoute
  '/sua-anh': typeof SuaAnhRoute
  '/tien-ich': typeof TienIchRoute
  '/tin-tuc': typeof TinTucRouteWithChildren
  '/tin-tuc/$slug': typeof TinTucSlugRoute
  '/tin-tuc/': typeof TinTucIndexRoute
  '/api/leads': typeof ApiLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/can-ho': typeof CanHoRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/kham-pha': typeof KhamPhaRoute
  '/lien-he': typeof LienHeRoute
  '/sua-anh': typeof SuaAnhRoute
  '/tien-ich': typeof TienIchRoute
  '/tin-tuc/$slug': typeof TinTucSlugRoute
  '/tin-tuc': typeof TinTucIndexRoute
  '/api/leads': typeof ApiLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/can-ho': typeof CanHoRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/kham-pha': typeof KhamPhaRoute
  '/lien-he': typeof LienHeRoute
  '/sua-anh': typeof SuaAnhRoute
  '/tien-ich': typeof TienIchRoute
  '/tin-tuc': typeof TinTucRouteWithChildren
  '/tin-tuc/$slug': typeof TinTucSlugRoute
  '/tin-tuc/': typeof TinTucIndexRoute
  '/api/leads': typeof ApiLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/can-ho'
    | '/gioi-thieu'
    | '/kham-pha'
    | '/lien-he'
    | '/sua-anh'
    | '/tien-ich'
    | '/tin-tuc'
    | '/tin-tuc/$slug'
    | '/tin-tuc/'
    | '/api/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/can-ho'
    | '/gioi-thieu'
    | '/kham-pha'
    | '/lien-he'
    | '/sua-anh'
    | '/tien-ich'
    | '/tin-tuc/$slug'
    | '/tin-tuc'
    | '/api/leads'
  id:
    | '__root__'
    | '/'
    | '/can-ho'
    | '/gioi-thieu'
    | '/kham-pha'
    | '/lien-he'
    | '/sua-anh'
    | '/tien-ich'
    | '/tin-tuc'
    | '/tin-tuc/$slug'
    | '/tin-tuc/'
    | '/api/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanHoRoute: typeof CanHoRoute
  GioiThieuRoute: typeof GioiThieuRoute
  KhamPhaRoute: typeof KhamPhaRoute
  LienHeRoute: typeof LienHeRoute
  SuaAnhRoute: typeof SuaAnhRoute
  TienIchRoute: typeof TienIchRoute
  TinTucRoute: typeof TinTucRouteWithChildren
  ApiLeadsRoute: typeof ApiLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/can-ho': {
      id: '/can-ho'
      path: '/can-ho'
      fullPath: '/can-ho'
      preLoaderRoute: typeof CanHoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kham-pha': {
      id: '/kham-pha'
      path: '/kham-pha'
      fullPath: '/kham-pha'
      preLoaderRoute: typeof KhamPhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sua-anh': {
      id: '/sua-anh'
      path: '/sua-anh'
      fullPath: '/sua-anh'
      preLoaderRoute: typeof SuaAnhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tien-ich': {
      id: '/tien-ich'
      path: '/tien-ich'
      fullPath: '/tien-ich'
      preLoaderRoute: typeof TienIchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-tuc': {
      id: '/tin-tuc'
      path: '/tin-tuc'
      fullPath: '/tin-tuc'
      preLoaderRoute: typeof TinTucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-tuc/': {
      id: '/tin-tuc/'
      path: '/'
      fullPath: '/tin-tuc/'
      preLoaderRoute: typeof TinTucIndexRouteImport
      parentRoute: typeof TinTucRoute
    }
    '/tin-tuc/$slug': {
      id: '/tin-tuc/$slug'
      path: '/$slug'
      fullPath: '/tin-tuc/$slug'
      preLoaderRoute: typeof TinTucSlugRouteImport
      parentRoute: typeof TinTucRoute
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TinTucRouteChildren {
  TinTucSlugRoute: typeof TinTucSlugRoute
  TinTucIndexRoute: typeof TinTucIndexRoute
}

const TinTucRouteChildren: TinTucRouteChildren = {
  TinTucSlugRoute: TinTucSlugRoute,
  TinTucIndexRoute: TinTucIndexRoute,
}

const TinTucRouteWithChildren =
  TinTucRoute._addFileChildren(TinTucRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanHoRoute: CanHoRoute,
  GioiThieuRoute: GioiThieuRoute,
  KhamPhaRoute: KhamPhaRoute,
  LienHeRoute: LienHeRoute,
  SuaAnhRoute: SuaAnhRoute,
  TienIchRoute: TienIchRoute,
  TinTucRoute: TinTucRouteWithChildren,
  ApiLeadsRoute: ApiLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
